const chapters = ["Assessment Test - Chapter 0","Cloud Technologies & Security - Chapter 18","Cryptography - Chapter 3","Denial of Service - Chapter 11","Enumeration - Chapter 6","Evasion - Chapter 17","Footprinting - Chapter 4","Hacking Wi-Fi & Bluetooth - Chapter 15","Introduction - Chapter 1","Malware - Chapter 8","Mobile Device Security - Chapter 16","Physical Security - Chapter 19","SQL Injection - Chapter 14","Scanning - Chapter 5","Session Hijacking - Chapter 12","Sniffers - Chapter 9","Social Engineering - Chapter 10","System Fundamentals - Chapter 2","System Hacking - Chapter 7","Web Server & Applications - Chapter 13"];
const state={questions:[],index:0,score:0,selected:null,checked:false};
const $=id=>document.getElementById(id);
const show=id=>document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));
function normalise(q){return {...q,answers:q.answers.map((a,i)=>{const m=a.match(/^([A-E])\)\s*(.*)$/);return m?{letter:m[1],text:m[2]}:{letter:String.fromCharCode(65+i),text:a};})};}
async function load(){const all=[];for(const chapter of chapters){try{const r=await fetch(`data/questions/${encodeURIComponent(chapter)}.json`);if(!r.ok)continue;const d=await r.json();all.push(...(d.questions||[]).map(normalise));}catch(e){console.warn(chapter,e);}}return all;}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function render(){const q=state.questions[state.index];$('progress').textContent=`Question ${state.index+1} of ${state.questions.length}`;$('score').textContent=`Score: ${state.score}`;$('question').textContent=q.question;$('answers').innerHTML='';$('feedback').textContent='';$('nextBtn').disabled=true;state.selected=null;state.checked=false;q.answers.forEach(a=>{const b=document.createElement('button');b.className='answer';b.textContent=`${a.letter}) ${a.text}`;b.addEventListener('click',()=>{if(state.checked)return;state.selected=a.letter;document.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');});$('answers').appendChild(b);});}
function start(amount){if(!state.questions.length){$('feedback').textContent='Question bank is still loading. Please try again.';return;}const pool=shuffle(state.questions);state.questions=amount?pool.slice(0,Math.min(amount,pool.length)):pool;state.index=0;state.score=0;show('quiz');render();}
$('startBtn').addEventListener('click',()=>start());$('randomBtn').addEventListener('click',()=>start(20));$('againBtn').addEventListener('click',()=>start(20));
$('checkBtn').addEventListener('click',()=>{if(state.selected===null||state.checked){$('feedback').textContent='Please select an answer first.';return;}state.checked=true;const q=state.questions[state.index];document.querySelectorAll('.answer').forEach(b=>{const l=b.textContent.trim()[0];if(l===q.correct)b.classList.add('correct');if(l===state.selected&&l!==q.correct)b.classList.add('wrong');});if(state.selected===q.correct){state.score++;$('feedback').textContent='Correct!';}else $('feedback').textContent=`Incorrect. Correct answer: ${q.correct}`;$('score').textContent=`Score: ${state.score}`;$('nextBtn').disabled=false;});
$('nextBtn').addEventListener('click',()=>{if(!state.checked)return;if(state.index>=state.questions.length-1){const pct=Math.round(state.score/state.questions.length*100);$('resultText').textContent=`You scored ${state.score} out of ${state.questions.length} (${pct}%).`;show('results');return;}state.index++;render();});
load().then(q=>{state.questions=q;document.querySelector('.note').textContent=q.length?`${q.length} questions loaded. Ready to practice.`:'Question bank could not be loaded.';}).catch(e=>console.error(e));
